### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by lockerbleiben** [nomensa/jquery.accessible-accordion#7]
Hey,
maybe you can add some animation to this wonderful script: :+1: 
e.g. 
- slide on tab change
- short color transition, when changing the tab

Thank you in advance :)

**Comment by anevins12** [comment]
Hi lockerbleiben, we've left animations out so that it will work for a wider range of people. As the accordion adds classes for these states, you can usually use CSS to style them how you want. 
I don't think you'll be able to achieve the slide, since the accordion just displays 'none' and 'block' the accordion content (and does not use top-to-bottom or left-to-right positioning), but I do think you can achieve a colour transition when changing tabs.
